--Creating Table for the Dataset

CREATE TABLE sales(
order_id INT,
customer_name VARCHAR(60),
order_date DATE,
category VARCHAR(50),
sub_category VARCHAR(50),
product_name VARCHAR(100),
quantity INT,
unit_price INT,
total_price INT,
region VARCHAR(50)
);

--Display all details of every order.

SELECT * FROM sales;

--Display the customer name, product name, and total price for all orders.

SELECT customer_name, product_name, total_price FROM sales;

--Display all orders where the category is 'Electronics'.

SELECT * FROM sales
WHERE category = 'Electronics';

--Find all orders where the quantity is greater than 5 and sort the results by quantity in descending order.

SELECT * FROM sales
WHERE quantity > 5
ORDER BY quantity DESC;

--Display all orders placed between 1st March 2025 and 31st May 2025.

SELECT * FROM sales
WHERE order_date BETWEEN '2025-03-01' AND '2025-03-31';

--Display the top 10 highest-value orders based on total_price.

SELECT * FROM sales
ORDER BY total_price DESC
LIMIT 10;

--Display all customers in alphabetical order.

SELECT * FROM sales
ORDER BY customer_name ASC;

--Find the total revenue generated from all sales.

SELECT ROUND(SUM(total_price), 2) FROM sales;

--Find the average order value.

SELECT ROUND(AVG(total_price), 2) FROM sales;

--Count the total number of orders.

SELECT COUNT(*) FROM sales;

--Find the total sales revenue generated by each category.

SELECT category, ROUND(SUM(total_price), 2)
FROM sales 
GROUP BY category;

--Find the average unit price for each category.

SELECT category, ROUND(AVG(unit_price), 2)
FROM sales 
GROUP BY category;

--Count the number of orders placed in each region.

SELECT region, COUNT(*)
FROM sales
GROUP BY region;

--Find the total quantity sold in each region.

SELECT region, SUM(quantity)
FROM sales
GROUP BY region;

--Find the category that generated the highest total revenue.

SELECT category, 
SUM(total_price) AS total_revenue
FROM sales
GROUP BY category
ORDER BY total_revenue DESC
LIMIT 1;

--Find all customers whose order value is greater than the average order value.

SELECT customer_name, SUM(total_price)
FROM sales
GROUP BY customer_name
HAVING SUM(total_price) > (
SELECT AVG(total_price)
FROM sales);

--Display each order along with a new column called Order_Size using the following conditions:
--Total Price > 20,000 → High Value
--Total Price between 10,000 and 20,000 → Medium Value
--Otherwise → Low Value

SELECT 
     order_id, customer_name, order_date, product_name, quantity, unit_price,
     CASE
	     WHEN total_price > 20000 THEN 'High Value'
		 WHEN total_price BETWEEN 10000 AND 20000 THEN 'Medium Value'
		 ELSE 'Low Value'
     END AS order_size
FROM sales;	 

--Find the most expensive product based on unit_price.

SELECT product_name, MAX(unit_price)
FROM sales
GROUP BY product_name
ORDER BY MAX(unit_price) DESC
LIMIT 1;

--Display the top 5 customers with the highest order values.

SELECT customer_name, SUM(total_price) AS order_value
FROM sales
GROUP BY customer_name
ORDER BY order_value DESC
LIMIT 5;

--Create a separate Sales table containing similar sales details and write a query to display:
-- .Customer Name
-- .Product Name
-- .Category
-- .Total Price
--using an INNER JOIN between the sales and customers tables

CREATE TABLE sales2(
order_id INT,
customer_name VARCHAR(60),
order_date DATE,
category VARCHAR(50),
sub_category VARCHAR(50),
product_name VARCHAR(100),
quantity INT,
unit_price INT,
total_price INT,
region VARCHAR(50)
);


SELECT sales.customer_name, sales.product_name, sales.category, sales.total_price
FROM sales
INNER JOIN sales2
ON sales.order_id = sales2.order_id;
